### ISSUE TITLE
Feature request: Fusing pointers to identical data

### ISSUE THREAD

**Issue by Tisten** [wc-duck/datalibrary#146] opened 2022-10-06 18:39 UTC
Merging of pointers (and arrays) which have identical payloads can save a lot of space. This could either be supported on a global file scale, or with a per pointer/array decorator which decides if fusing the data is valid for that pointer or not. Global support is a great start.

**Comment by wc-duck** [comment] 2022-10-06 19:36
Duplicate of issue #14

**Closed** 2022-10-07 06:18 UTC
